public static class PhraseList
{
    public static string[] phrases =
    {
        "FUNemployment",
        "Has wires", "The Original", "Mostly black", "Has a\ncipher", "Flashes colors", "Press a Pixel", "Order! Order!", "Look Around",
        "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages", "Iconic", "Organization", "Forget Perspective",
        "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages", "Iconic", "Organization", "Forget Perspective", "Forget Them All",
        "Souvenir", "Forget Enigma", "Simon's Stages", "Iconic", "Organization", "Forget Perspective", "Forget Them All", "Forget Me Not",
        "Forget Enigma", "Simon's Stages", "Iconic", "Organization", "Forget Perspective", "Forget Them All", "Forget Me Not", "Souvenir",
        "Simon's Stages", "Iconic", "Organization", "Forget Perspective", "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma",
        "Iconic", "Organization", "Forget Perspective", "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages",
        "Organization", "Forget Perspective", "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages", "Iconic",
        "Come again?",
        "Cardinals", "Colored Flags", "Dashes and dots", "Sound Occurrence", "Speakingevil", "Minecraft", "Pork", "Blind",
        "Semaphore", "Maritime", "Morse Code", "Tap Code", "Boozleglyph", "Standard Galactic Alphabet", "Pigpen", "Braille",
        "Maritime", "Morse Code", "Tap Code", "Boozleglyph", "Standard Galactic Alphabet", "Pigpen", "Braille", "Semaphore",
        "Morse Code", "Tap Code", "Boozleglyph", "Standard Galactic Alphabet", "Pigpen", "Braille", "Semaphore", "Maritime",
        "Tap Code", "Boozleglyph", "Standard Galactic Alphabet", "Pigpen", "Braille", "Semaphore", "Maritime", "Morse Code",
        "Boozleglyph", "Standard Galactic Alphabet", "Pigpen", "Braille", "Semaphore", "Maritime", "Morse Code", "Tap Code",
        "Standard Galactic Alphabet", "Pigpen", "Braille", "Semaphore", "Maritime", "Morse Code", "Tap Code", "Boozleglyph",
        "Pigpen", "Braille", "Semaphore", "Maritime", "Morse Code", "Tap Code", "Boozleglyph", "Standard Galactic Alphabet",
        "Unicode",
        "BFFs", "Multidimensional", "Ones and Zeros", "You're a Wizard", "Poetic", "Traffic Jam", "TV Show", "Blank",
        "Friendship", "Hypercube", "Binary Puzzle", "Hogwarts", "Kudosudoku", "Gridlock", "Only Connect", "Blind Alley",
        "Hypercube", "Binary Puzzle", "Hogwarts", "Kudosudoku", "Gridlock", "Only Connect", "Blind Alley", "Friendship",
        "Binary Puzzle", "Hogwarts", "Kudosudoku", "Gridlock", "Only Connect", "Blind Alley", "Friendship", "Hypercube",
        "Hogwarts", "Kudosudoku", "Gridlock", "Only Connect", "Blind Alley", "Friendship", "Hypercube", "Binary Puzzle",
        "Kudosudoku", "Gridlock", "Only Connect", "Blind Alley", "Friendship", "Hypercube", "Binary Puzzle", "Hogwarts",
        "Gridlock", "Only Connect", "Blind Alley", "Friendship", "Hypercube", "Binary Puzzle", "Hogwarts", "Kudosudoku",
        "Only Connect", "Blind Alley", "Friendship", "Hypercube", "Binary Puzzle", "Hogwarts", "Kudosudoku", "Gridlock",
        "Best Hand",
        "Royal Flush", "Blue Creature", "4 8 15 16 23 42", "Fus Ro Dah!", "Star Trek", "Halloween", "The Clock", "Ancient Egypt",
        "Poker", "Sonic The Hedgehog", "The Swan", "Skyrim", "Lightspeed", "The Jack-O'-Lantern", "Countdown", "Hieroglyphics",
        "Sonic The Hedgehog", "The Swan", "Skyrim", "Lightspeed", "The Jack-O'-Lantern", "Countdown", "Hieroglyphics", "Poker",
        "The Swan", "Skyrim", "Lightspeed", "The Jack-O'-Lantern", "Countdown", "Hieroglyphics", "Poker", "Sonic The Hedgehog",
        "Skyrim", "Lightspeed", "The Jack-O'-Lantern", "Countdown", "Hieroglyphics", "Poker", "Sonic The Hedgehog", "The Swan",
        "Lightspeed", "The Jack-O'-Lantern", "Countdown", "Hieroglyphics", "Poker", "Sonic The Hedgehog", "The Swan", "Skyrim",
        "The Jack-O'-Lantern", "Countdown", "Hieroglyphics", "Poker", "Sonic The Hedgehog", "The Swan", "Skyrim", "Lightspeed",
        "Countdown", "Hieroglyphics", "Poker", "Sonic The Hedgehog", "The Swan", "Skyrim", "Lightspeed", "The Jack-O'-Lantern",
        "Musical Chairs",
        "Pitch Comparison", "Red Background", "Hardware Store", "Choir", "BPM", "Green Background", "Swap Parts", "Cha Cha Real Smooth",
        "Intervals", "Cruel Piano Keys", "Weird Al Yankovic", "Simon Sings", "Time Signatures", "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky",
        "Cruel Piano Keys", "Weird Al Yankovic", "Simon Sings", "Time Signatures", "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky", "Intervals",
        "Weird Al Yankovic", "Simon Sings", "Time Signatures", "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky", "Intervals", "Cruel Piano Keys",
        "Simon Sings", "Time Signatures", "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky", "Intervals", "Cruel Piano Keys", "Weird Al Yankovic",
        "Time Signatures", "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky", "Intervals", "Cruel Piano Keys", "Weird Al Yankovic", "Simon Sings",
        "Festive Piano Keys", "Melody Sequencer", "Gettin' Funky", "Intervals", "Cruel Piano Keys", "Weird Al Yankovic", "Simon Sings", "Time Signatures",
        "Melody Sequencer", "Gettin' Funky", "Intervals", "Cruel Piano Keys", "Weird Al Yankovic", "Simon Sings", "Time Signatures", "Festive Piano Keys",
        "I am Lost",
        "Manufacturing", "Make Your Maze", "The Original", "Cubic Maze", "Straight Line", "Patriotic", "Swedish Maze", "Color Addition",
        "Factory Maze", "ASCII Maze", "Maze", "Maze³", "1D Maze", "USA Maze", "IKEA", "RGB Maze",
        "ASCII Maze", "Maze", "Maze³", "1D Maze", "USA Maze", "IKEA", "RGB Maze", "Factory Maze",
        "Maze", "Maze³", "1D Maze", "USA Maze", "IKEA", "RGB Maze", "Factory Maze", "ASCII Maze",
        "Maze³", "1D Maze", "USA Maze", "IKEA", "RGB Maze", "Factory Maze", "ASCII Maze", "Maze",
        "1D Maze", "USA Maze", "IKEA", "RGB Maze", "Factory Maze", "ASCII Maze", "Maze", "Maze³",
        "USA Maze", "IKEA", "RGB Maze", "Factory Maze", "ASCII Maze", "Maze", "Maze³", "1D Maze",
        "IKEA", "RGB Maze", "Factory Maze", "ASCII Maze", "Maze", "Maze³", "1D Maze", "USA Maze",
        "Identity Crisis",
        "Math Intensive", "Boss Module", "Piano", "Color Addition", "Octagonal", "Amalgamation", "The Original", "Nonverbal",
        "Simon Stores", "Simon's Stages", "Simon Sings", "Simon Sends", "Simon Stops", "Simon's Ultimate Showdown", "Simon Says", "❖",
        "Simon's Stages", "Simon Sings", "Simon Sends", "Simon Stops", "Simon's Ultimate Showdown", "Simon Says", "❖", "Simon Stores",
        "Simon Sings", "Simon Sends", "Simon Stops", "Simon's Ultimate Showdown", "Simon Says", "❖", "Simon Stores", "Simon's Stages",
        "Simon Sends", "Simon Stops", "Simon's Ultimate Showdown", "Simon Says", "❖", "Simon Stores", "Simon's Stages", "Simon Sings",
        "Simon Stops", "Simon's Ultimate Showdown", "Simon Says", "❖", "Simon Stores", "Simon's Stages", "Simon Sings", "Simon Sends",
        "Simon's Ultimate Showdown", "Simon Says", "❖", "Simon Stores", "Simon's Stages", "Simon Sings", "Simon Sends", "Simon Stops",
        "Simon Says", "❖", "Simon Stores", "Simon's Stages", "Simon Sings", "Simon Sends", "Simon Stops", "Simon's Ultimate Showdown",
        "Take This!",
        "Elixir", "Use if Short", "Never Propser", "Winner", "See into the Future", "Night light", "Sunlight", "Powered",
        "Potion", "Stepladder", "Cheat Code", "Trophy", "Crystal Ball", "Moonstone", "Sunstone", "Battery",
        "Stepladder", "Cheat Code", "Trophy", "Crystal Ball", "Moonstone", "Sunstone", "Battery", "Potion",
        "Cheat Code", "Trophy", "Crystal Ball", "Moonstone", "Sunstone", "Battery", "Potion", "Stepladder",
        "Trophy", "Crystal Ball", "Moonstone", "Sunstone", "Battery", "Potion", "Stepladder", "Cheat Code",
        "Crystal Ball", "Moonstone", "Sunstone", "Battery", "Potion", "Stepladder", "Cheat Code", "Trophy",
        "Moonstone", "Sunstone", "Battery", "Potion", "Stepladder", "Cheat Code", "Trophy", "Crystal Ball",
        "Sunstone", "Battery", "Potion", "Stepladder", "Cheat Code", "Trophy", "Crystal Ball", "Moonstone",
        "Forget Me Not",
        "Bit Bit", "Crank the Lever", "Primal Rage", "Hang Them", "Literature Club", "Colorblind Mode", "Hell", "Balanced Ternary",
        "Two Bits", "Silly Slots", "Hunting", "Mafia", "Poetry", "Visual Impairment", "Necronomicon", "Simon Stores",
        "Silly Slots", "Hunting", "Mafia", "Poetry", "Visual Impairment", "Necronomicon", "Simon Stores", "Two Bits",
        "Hunting", "Mafia", "Poetry", "Visual Impairment", "Necronomicon", "Simon Stores", "Two Bits", "Silly Slots",
        "Mafia", "Poetry", "Visual Impairment", "Necronomicon", "Simon Stores", "Two Bits", "Silly Slots", "Hunting",
        "Poetry", "Visual Impairment", "Necronomicon", "Simon Stores", "Two Bits", "Silly Slots", "Hunting", "Mafia",
        "Visual Impairment", "Necronomicon", "Simon Stores", "Two Bits", "Silly Slots", "Hunting", "Mafia", "Poetry",
        "Necronomicon", "Simon Stores", "Two Bits", "Silly Slots", "Hunting", "Mafia", "Poetry", "Visual Impairment",
        "Double Down",
        "Cashing Out", "Twenty One", "Machine", "Mao", "Bluffing", "Worst Hand", "Coin Toss", "Seven Cards",
        "Four-Card Monte", "Blackjack", "Silly Slots", "Point of Order", "Poker", "Badugi", "Flip The Coin", "Bridge",
        "Blackjack", "Silly Slots", "Point of Order", "Poker", "Badugi", "Flip The Coin", "Bridge", "Four-Card Monte",
        "Silly Slots", "Point of Order", "Poker", "Badugi", "Flip The Coin", "Bridge", "Four-Card Monte", "Blackjack",
        "Point of Order", "Poker", "Badugi", "Flip The Coin", "Bridge", "Four-Card Monte", "Blackjack", "Silly Slots",
        "Poker", "Badugi", "Flip The Coin", "Bridge", "Four-Card Monte", "Blackjack", "Silly Slots", "Point of Order",
        "Badugi", "Flip The Coin", "Bridge", "Four-Card Monte", "Blackjack", "Silly Slots", "Point of Order", "Poker",
        "Flip The Coin", "Bridge", "Four-Card Monte", "Blackjack", "Silly Slots", "Point of Order", "Poker", "Badugi",
        //My bodgy solution to a weird bug I keep getting
        "Rick Astley",
        "Never", "Gonna", "Give", "You", "Up", "Never", "Gonna", "Let",
        "You", "Down", "Never", "Gonna", "Run", "Around", "And", "Desert",
        "You", "Never", "Gonna", "Make", "You", "Cry", "Never", "Gonna",
        "Say", "Goodbye", "Never", "Gonna", "Tell", "A", "Lie", "And",
        "Hurt", "You"
    };
}
